# Generated by Django 4.0.3 on 2022-04-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_alter_comment_post_alter_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
