# Generated by Django 4.0.3 on 2022-04-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0006_alter_comment_commented_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-published_on']},
        ),
    ]
